# Generated by Django 5.1.3 on 2024-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
